services:
  php-epg:
    image: taksss/php-epg:latest
    container_name: php-epg
    # 数据目录映射
    volumes:
      - /etc/epg:/htdocs/data
    # 默认端口 5678
    ports:
      - "5678:80"
    depends_on:
      - mysql
      - phpmyadmin
    restart: unless-stopped 

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: phpepg
      MYSQL_USER: phpepg
      MYSQL_PASSWORD: phpepg
    restart: unless-stopped 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    restart: unless-stopped 