name: Update Icon List

#on:
#  schedule:
#    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-icon-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download iconList_default.json
        run: |
          curl -sL https://github.com/taksssss/tv/raw/refs/heads/main/iconList_default.json -o epg/iconList_default.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add epg/iconList_default.json
          git diff --cached --quiet || git commit -m "Update iconList_default.json"
          git push
